# Generated by Django 4.2.3 on 2023-07-18 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id_Tester', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=45, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellido M')),
                ('fechaNac', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(max_length=50, null=True, verbose_name='Correo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('userType', models.CharField(default='Tester', max_length=20, verbose_name='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testerUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id_Experto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=45, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellido M')),
                ('fechaNac', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(max_length=50, null=True, verbose_name='Correo')),
                ('institucionPerteneciente', models.CharField(max_length=100, verbose_name='Institución a la que pertenece')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('userType', models.CharField(default='Experto', max_length=20, verbose_name='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertoUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_Administrador', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID_Administrador')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=45, verbose_name='Apellido P')),
                ('apellidoM', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Apellido M')),
                ('fechaNac', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Correo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('userType', models.CharField(default='Administrador', max_length=20, verbose_name='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradorUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario')),
            ],
        ),
    ]
