# Generated by Django 4.2.3 on 2023-07-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
