# Generated by Django 4.2.3 on 2023-07-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0002_alter_administrador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
