# Generated by Django 4.2.3 on 2023-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0009_alter_dataset_nombredataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='nombreEnfermedad',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre de la Enfermedad'),
        ),
    ]
