# Generated by Django 4.2.3 on 2023-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0010_alter_enfermedad_nombreenfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='imagen',
            field=models.ImageField(default='imagenes/defaultProfile.png', upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='experto',
            name='imagen',
            field=models.ImageField(default='imagenes/defaultProfile.png', upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='imagen',
            field=models.ImageField(default='imagenes/defaultProfile.png', upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
