# Generated by Django 4.2.3 on 2023-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0012_alter_dataset_numimgentrenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
