# Generated by Django 4.2.3 on 2023-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0013_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='experto',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
