# Generated by Django 4.2.3 on 2023-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0014_administrador_token_experto_token_tester_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_Cultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCultivo', models.CharField(max_length=45, unique=True, verbose_name='Nombre del Cultivo')),
                ('descripcionCultivo', models.TextField(max_length=200, verbose_name='Descripción del cultivo')),
            ],
        ),
    ]
