# Generated by Django 4.2.3 on 2023-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0024_modelo_yolov7_delete_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='pesosModelo_y7',
            field=models.FileField(help_text='Selecciona un archivo de pesos correcto', upload_to='modelos/yolov7/', verbose_name='Ruta de Pesos'),
        ),
    ]
