# Generated by Django 4.2.3 on 2023-10-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0026_remove_dataset_tipodataset_dataset_numclases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermedad',
            old_name='curaEnfermedad',
            new_name='tratamientoEnfermedad',
        ),
    ]
