# Generated by Django 4.2.3 on 2023-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0027_rename_curaenfermedad_enfermedad_tratamientoenfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='batch_size_y7',
            field=models.IntegerField(verbose_name='Batch Size'),
        ),
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='epocas_y7',
            field=models.IntegerField(verbose_name='Número de épocas'),
        ),
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='pesosModelo_y7',
            field=models.FileField(upload_to='weights/yolov7/', verbose_name='Ruta de Pesos'),
        ),
    ]
