# Generated by Django 4.2.3 on 2023-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0030_modelo_transformer_datasetmodelo_transformer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_transformer',
            name='batch_size_transformer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4)], verbose_name='Batch Size'),
        ),
    ]
