# Generated by Django 4.2.3 on 2023-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0031_alter_modelo_transformer_batch_size_transformer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_transformer',
            name='batch_size_transformer',
            field=models.IntegerField(verbose_name='Batch Size'),
        ),
    ]
