# Generated by Django 4.2.3 on 2023-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0032_alter_modelo_transformer_batch_size_transformer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_transformer',
            name='pesosModelo_transformer',
            field=models.FileField(blank=True, null=True, upload_to='weights/Transformer/', verbose_name='Ruta de Pesos'),
        ),
    ]
