# Generated by Django 4.2.3 on 2023-11-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0034_dataset_tipodataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_yolov7',
            name='accuracy_y7',
            field=models.FloatField(blank=True, null=True, verbose_name='Accuracy'),
        ),
        migrations.AddField(
            model_name='modelo_yolov7',
            name='datasetModelo_y7',
            field=models.ForeignKey(default=207, on_delete=django.db.models.deletion.CASCADE, related_name='y7Dataset', to='AppSafeCrops.dataset', verbose_name='Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo_yolov7',
            name='loss_y7',
            field=models.FloatField(blank=True, null=True, verbose_name='Loss'),
        ),
        migrations.AddField(
            model_name='modelo_yolov7',
            name='ruta_resultados_y7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta de resultados'),
        ),
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='pesosModelo_y7',
            field=models.FileField(upload_to='weights/YOLOv7/', verbose_name='Ruta de Pesos'),
        ),
    ]
