# Generated by Django 4.2.3 on 2023-11-08 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppSafeCrops', '0035_modelo_yolov7_accuracy_y7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_transformer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformerUser', to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario'),
        ),
    ]
