# Generated by Django 4.2.3 on 2023-11-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSafeCrops', '0036_modelo_transformer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_transformer',
            name='f1Score_transformer',
            field=models.FloatField(blank=True, null=True, verbose_name='F1 Score'),
        ),
        migrations.AddField(
            model_name='modelo_yolov7',
            name='f1Score_y5',
            field=models.FloatField(blank=True, null=True, verbose_name='F1 Score'),
        ),
        migrations.AlterField(
            model_name='modelo_yolov7',
            name='pesosModelo_y7',
            field=models.FileField(blank=True, null=True, upload_to='weights/YOLOv7/', verbose_name='Ruta de Pesos'),
        ),
        migrations.CreateModel(
            name='Modelo_YOLOv5',
            fields=[
                ('id_Modelo_y5', models.AutoField(primary_key=True, serialize=False)),
                ('nombreModelo_y5', models.CharField(max_length=45, unique=True, verbose_name='Nombre del Modelo')),
                ('pesosModelo_y5', models.FileField(blank=True, null=True, upload_to='weights/YOLOv5/', verbose_name='Ruta de Pesos')),
                ('epocas_y5', models.IntegerField(verbose_name='Número de épocas')),
                ('batch_size_y5', models.IntegerField(verbose_name='Batch Size')),
                ('accuracy_y5', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('loss_y5', models.FloatField(blank=True, null=True, verbose_name='Loss')),
                ('f1Score_y5', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('ruta_resultados_y5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta de resultados')),
                ('datasetModelo_y5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y5Dataset', to='AppSafeCrops.dataset', verbose_name='Dataset')),
            ],
        ),
    ]
