"""
Django settings for SafeCrops project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lz2ofcxe6if=307hrjk=xf)jw8^y9dl&o^+8s*c0a@_xc5p(0g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppSafeCrops',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

ROOT_URLCONF = 'SafeCrops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
            'menu': 'AppSafeCrops.templatetags.menu',
            
            }
        },
    },
]

WSGI_APPLICATION = 'SafeCrops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'id21050120_safecrops',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        # 'NAME': 'id21050120_safecrops',
        # 'USER': 'id21050120_root',
        # 'PASSWORD': 'SCdatabase13*_*',
        # 'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/' #imagenes de la BD
STATIC_ROOT = os.path.join(BASE_DIR, "static") #archivo estatico CSS

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

MEDIA_ROOT = os.path.join(BASE_DIR, '')
MEDIA_URL = '/imagenes/'
MEDIA_URL_DATASET = '/datasets/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login'
REGISTRATION_REDIRECT_URL = '/registration'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'djangosafecrops@gmail.com'
EMAIL_HOST_PASSWORD = 'sqdlznehyinrpgtr'
EMAIL_USE_TLS = True
DOMAIN = ''

# Configuración de sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # Almacena las sesiones en la base de datos
SESSION_COOKIE_NAME = 'session_cookie' # Nombre de la cookie de sesión
SESSION_COOKIE_AGE = 3600 # Duración de la sesión en segundos (1 hora)
SESSION_SAVE_EVERY_REQUEST = True # Actualizar la última actividad en cada solicitud

# Tiempo de inactividad para expirar la sesión (en segundos)
SESSION_COOKIE_IDLE_TIMEOUT = 30 # 30 segundos de inactividad antes de la expiración
